#localhost:8014/swagger-ui.html
server:
  port: 80

spring:
  profiles: dev
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#  instance:
#    # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
#    lease-renewal-interval-in-seconds: 1
#    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
#    lease-expiration-duration-in-seconds: 2

#http://localhost/zuulA/serviceA/test
zuul:
  #开启重试机制
  retryable: true
  routes:
    service-A-service:
      path: /zuulA/**
      serviceId: service-A-server
ribbon:
  ReadTimeout: 1000  # 单位毫秒数
  SocketTimeout: 1000
  ##对当前服务的重试次数
  MaxAutoRetries: 3
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0
#  ratelimit:
#    enabled: true
#    default-policy:
#      limit: 1
#      #quota: 1
#      refresh-interval: 3
#    policies:
#      service-A-service:
#        #每个刷新时间窗口对应的请求数量限制
#        limit: 5
#        #每个刷新时间窗口对应的请求时间限制（秒）
#        #quota: 50
#        #刷新时间窗口的时间，默认值 (秒)
#        refresh-interval: 20